steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/light-truth-353823/github.com/mokubatek/mokubatek:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/light-truth-353823/github.com/mokubatek/mokubatek:$COMMIT_SHA']
